### ISSUE TITLE
Nonexistent pytorch_perciever.

### ISSUE THREAD

**Issue by kaitsmith22** [pliang279/HighMMT#1]
Hello! When I run `python private_test_scripts/perceivers/singletask.py`, I get the error `Traceback (most recent call last):
  File "private_test_scripts/perceivers/singletask.py", line 5, in <module>
    from private_test_scripts.perceivers.crossattnperceiver import MultiModalityPerceiver, InputModality
  File "/run/determined/workdir/irad_users/smithk/nlp/HighMMT/HighMMT/private_test_scripts/perceivers/crossattnperceiver.py", line 9, in <module>
    from perceiver_pytorch.caching import cache_by_name_fn
ModuleNotFoundError: No module named 'perceiver_pytorch.caching'`. Could you push the `perceiver_pytorch` module?

**Comment by lvyiwei1** [comment]
Please follow the instructions at this repository to install perceiver_pytorch: https://github.com/fac2003/perceiver-multi-modality-pytorch

**Comment by SimoneMayday** [comment]
Hello, I have already based on https://github.com/fac2003/perceiver-multi-modality-pytorch Installed perceiver-multi-modality-pytorch and perceiver_pytorch, but when running Python private_test_stcripts/perceivers/roboticsTask. py model. pt

Still reporting error: Traceback (most recent call last):

File "private_test_scripts/perceivers/roboticstasks.py", line 6, in <module>

from private_test_scripts.perceivers.crossattnperceiver import MultiModalityPerceiver, InputModality

File "/root/private_test_scripts/perceivers/crossattnperceiver.py", line 11, in <module>

from perceiver_pytorch.perceiver_pytorch import PreNorm, Attention, FeedForward, cache_fn, fourier_encode, \

ImportError: cannot import name 'FeedForwardGELU' from 'perceiver_pytorch.perceiver_pytorch' (/root/anaconda3/envs/jtsaw/lib/python3.8/site-packages/perceiver_pytorch/perceiver_pytorch.py)

May I ask what the reason is?
